In [1]:
# TensorFlow and tf.keras
import math
import tensorflow as tf
import numpy as np
from tensorflow import keras


#tf version should be 2.5 or higher
tf.__version__

'2.6.0'

In [2]:
#get data
(train_images, train_labels), (test_images, test_labels) = \
      keras.datasets.mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [3]:
#scale model
train_images = train_images / 255.0
test_images = test_images / 255.0

In [4]:
#reshape
train_images=train_images.reshape(train_images.shape[0],28,28,1)
test_images=test_images.reshape(test_images.shape[0],28,28,1)

In [5]:
#setup model
model = keras.Sequential([
   
    
    keras.layers.Conv2D(kernel_size=3, filters=32, use_bias=False, padding='same', input_shape=(28, 28 , 1)),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Activation('relu'),
    
    
    #tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=2),
    
    
    
    keras.layers.Conv2D(kernel_size=6, filters=64, use_bias=False, padding='same', strides=2),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Activation('relu'),
    
    #tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=2),
    
   
    
    keras.layers.Conv2D(kernel_size=6, filters=64, use_bias=False, padding='same', strides=2),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Activation('relu'),
    
        
    
    #tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=2),
    
   
    
    keras.layers.Flatten(),
    
    keras.layers.Dense(256, use_bias=False),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Activation('relu'),
    keras.layers.Dropout(0.3),
    
    keras.layers.Dense(128, use_bias=False),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Activation('relu'),
    keras.layers.Dropout(0.3),
    
    keras.layers.Dense(64, use_bias=False),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Activation('relu'),
    keras.layers.Dropout(0.3),
    
    keras.layers.Dense(10, activation = tf.nn.softmax)
])

In [6]:
#compile model
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
          loss='sparse_categorical_crossentropy',
          metrics=['accuracy'])

In [7]:
def lr_decay(epoch):
    return 0.01*math.pow(0.6, epoch)

lr_decay_callback=tf.keras.callbacks.LearningRateScheduler(lr_decay)

In [8]:
#train model
model.fit(train_images, train_labels, epochs=10, callbacks=[lr_decay_callback])

Epoch 1/10
1875/1875 [==============================] - 247s 131ms/step - loss: 0.2138 - accuracy: 0.9398
Epoch 2/10
1875/1875 [==============================] - 245s 131ms/step - loss: 0.0844 - accuracy: 0.9768
Epoch 3/10
1875/1875 [==============================] - 244s 130ms/step - loss: 0.0531 - accuracy: 0.9860
Epoch 4/10
1875/1875 [==============================] - 244s 130ms/step - loss: 0.0378 - accuracy: 0.9897
Epoch 5/10
1875/1875 [==============================] - 245s 130ms/step - loss: 0.0257 - accuracy: 0.9932
Epoch 6/10
1875/1875 [==============================] - 245s 131ms/step - loss: 0.0177 - accuracy: 0.9947
Epoch 7/10
1875/1875 [==============================] - 246s 131ms/step - loss: 0.0141 - accuracy: 0.9958
Epoch 8/10
1875/1875 [==============================] - 247s 132ms/step - loss: 0.0118 - accuracy: 0.9967
Epoch 9/10
1875/1875 [==============================] - 250s 133ms/step - loss: 0.0096 - accuracy: 0.9973
Epoch 10/10
1875/1875 [=======================

In [9]:
#evaluate
test_loss, test_acc = model.evaluate(test_images,  test_labels)
print('\nTest accuracy:', test_acc)

313/313 [==============================] - 8s 25ms/step - loss: 0.0163 - accuracy: 0.9950

Test accuracy: 0.9950000047683716


In [ ]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

In [ ]:
#Raw predictions
predictions

array([[1.2523764e-09, 9.1230100e-07, 4.7761762e-07, 8.9712466e-07,
        4.4385740e-07, 4.1498016e-08, 9.2217969e-12, 9.9999559e-01,
        5.4965977e-08, 1.4967979e-06],
       [8.5884686e-08, 1.6424811e-07, 9.9999952e-01, 1.2873276e-08,
        2.5538798e-08, 1.5080331e-11, 2.2825381e-08, 1.4704415e-07,
        2.3606546e-09, 2.5330786e-11],
       [2.7234444e-11, 9.9999940e-01, 2.5297253e-09, 3.5369414e-09,
        9.0597830e-08, 1.1610818e-08, 2.6518030e-08, 3.0610499e-07,
        7.4357622e-08, 1.4459318e-09],
       [9.9999976e-01, 8.6670966e-12, 2.5627600e-09, 5.8724264e-10,
        9.4014657e-11, 2.4910289e-09, 1.8254835e-07, 2.4355520e-10,
        1.0425596e-08, 1.3563608e-08],
       [1.1657989e-09, 2.2025401e-07, 1.2701255e-08, 2.8270347e-10,
        9.9998403e-01, 1.4407981e-08, 5.4962722e-08, 2.1084951e-08,
        9.2523301e-08, 1.5554180e-05]], dtype=float32)

In [ ]:
# Print our model's predictions
print(np.argmax(predictions, axis=1))

[7 2 1 0 4]


In [ ]:
# Check our predictions against the ground truths
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
